import { PhysicsBodyState, TracyZone } from "./types";

export const INITIAL_PHYSICS_BODIES: PhysicsBodyState[] = [
  {
    id: "phys-hero-mech",
    actorId: "actor-hero-mech",
    shape: "Capsule",
    motionType: "Dynamic",
    massKg: 750.0,
    friction: 0.6,
    restitution: 0.25,
    linearVelocity: [0, 0, 0],
    angularVelocity: [0, 0, 0],
    collisionLayer: "MOVING",
    active: true,
  },
  {
    id: "phys-crate",
    actorId: "actor-physics-box",
    shape: "Box",
    motionType: "Dynamic",
    massKg: 120.0,
    friction: 0.8,
    restitution: 0.15,
    linearVelocity: [0, 0, 0],
    angularVelocity: [0, 0, 0],
    collisionLayer: "MOVING",
    active: true,
  },
  {
    id: "phys-floor",
    actorId: "actor-terrain-floor",
    shape: "Box",
    motionType: "Static",
    massKg: 0.0,
    friction: 0.9,
    restitution: 0.05,
    linearVelocity: [0, 0, 0],
    angularVelocity: [0, 0, 0],
    collisionLayer: "NON_MOVING",
    active: true,
  },
];

export const TRACY_FRAME_ZONES: TracyZone[] = [
  {
    name: "Engine::MainLoopTick",
    durationMs: 16.24,
    percentage: 100.0,
    color: "#3b82f6",
    callstack: "Engine::Run() -> Engine::Tick()",
    category: "Core",
  },
  {
    name: "SDL3::PollEvents",
    durationMs: 0.18,
    percentage: 1.1,
    color: "#60a5fa",
    callstack: "Window::PollEvents() -> SDL_PollEvent()",
    category: "Core",
  },
  {
    name: "JoltPhysics::StepSimulation",
    durationMs: 2.15,
    percentage: 13.2,
    color: "#f59e0b",
    callstack: "PhysicsSystem::Update(dt) -> JPH::PhysicsSystem::Update()",
    category: "Physics",
  },
  {
    name: "SceneGraph::UpdateTransforms",
    durationMs: 0.42,
    percentage: 2.6,
    color: "#10b981",
    callstack: "SceneGraph::PropagateTransforms() -> SIMD Matrix Mult",
    category: "Core",
  },
  {
    name: "FrustumCulling::ExecuteAABB",
    durationMs: 0.28,
    percentage: 1.7,
    color: "#10b981",
    callstack: "FrustumCuller::CullVisibleActors()",
    category: "Core",
  },
  {
    name: "RenderGraph::CompileDAG",
    durationMs: 0.35,
    percentage: 2.1,
    color: "#8b5cf6",
    callstack: "RenderGraph::Compile() -> TopologicalSort & BarrierResolve",
    category: "RenderGraph",
  },
  {
    name: "Vulkan::ExecuteCommandBuffers",
    durationMs: 9.85,
    percentage: 60.6,
    color: "#ec4899",
    callstack: "RenderGraph::Execute() -> vkQueueSubmit2KHR()",
    category: "RHI",
  },
  {
    name: "DearImGui::DockingRender",
    durationMs: 1.82,
    percentage: 11.2,
    color: "#06b6d4",
    callstack: "EditorLayer::OnRender() -> ImGui_ImplVulkan_RenderDrawData()",
    category: "Editor",
  },
  {
    name: "Vulkan::PresentFrame",
    durationMs: 1.19,
    percentage: 7.3,
    color: "#ec4899",
    callstack: "VulkanContext::Present() -> vkQueuePresentKHR()",
    category: "RHI",
  },
];
