plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vanguard.engine'
    compileSdk 36
    ndkVersion '27.0.12077973'

    defaultConfig {
        applicationId 'com.vanguard.engine'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++23 -DANDROID -DVANGUARD_PLATFORM_ANDROID=1'
                abiFilters 'arm64-v8a'
            }
        }
    }

    externalNativeBuild {
        cmake {
            version '3.22.1'
            path 'src/main/cpp/CMakeLists.txt'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            ndk { debugSymbolLevel 'NONE' }
        }
    }

    packagingOptions {
        doNotStrip '**/libvanguard.so'
    }
}

dependencies {
}