import { ClassMetadata, EngineActor, EngineComponent, PropertyMetadata, TypeKind } from "./types";

export const REFLECTED_CLASSES: Record<string, ClassMetadata> = {
  TransformComponent: {
    className: "TransformComponent",
    parentClassName: "Component",
    size: 48, // 3*12 bytes + flags
    category: "Core",
    properties: [
      {
        name: "m_LocalPosition",
        displayName: "Position",
        type: TypeKind.Vec3,
        offset: 0,
        size: 12,
        category: "Transform",
        tooltip: "Translation relative to parent coordinate frame (GLM vec3)",
        step: 0.1,
      },
      {
        name: "m_LocalRotation",
        displayName: "Rotation (Euler)",
        type: TypeKind.Vec3,
        offset: 12,
        size: 12,
        category: "Transform",
        tooltip: "Euler angles in degrees (pitch, yaw, roll)",
        step: 1.0,
      },
      {
        name: "m_LocalScale",
        displayName: "Scale",
        type: TypeKind.Vec3,
        offset: 24,
        size: 12,
        category: "Transform",
        tooltip: "Scale vector along local XYZ axes",
        step: 0.05,
      },
      {
        name: "m_bIsStatic",
        displayName: "Is Static",
        type: TypeKind.Bool,
        offset: 36,
        size: 1,
        category: "Optimization",
        tooltip: "Static objects are pre-baked into acceleration structures and skip dirty transform checks.",
      },
    ],
  },

  StaticMeshComponent: {
    className: "StaticMeshComponent",
    parentClassName: "Component",
    size: 64,
    category: "Rendering",
    properties: [
      {
        name: "m_MeshAssetHandle",
        displayName: "Mesh Asset",
        type: TypeKind.AssetHandle,
        offset: 0,
        size: 16,
        category: "Geometry",
        tooltip: "GUID reference to compiled .vmesh binary geometry asset.",
      },
      {
        name: "m_MaterialAssetHandle",
        displayName: "Material Asset",
        type: TypeKind.AssetHandle,
        offset: 16,
        size: 16,
        category: "Shading",
        tooltip: "GUID reference to PBR material definition.",
      },
      {
        name: "m_bCastShadows",
        displayName: "Cast Shadows",
        type: TypeKind.Bool,
        offset: 32,
        size: 1,
        category: "Lighting",
        tooltip: "Enables rendering this mesh into the ShadowMap pass pipeline.",
      },
      {
        name: "m_bReceiveDecals",
        displayName: "Receive Decals",
        type: TypeKind.Bool,
        offset: 33,
        size: 1,
        category: "Lighting",
      },
      {
        name: "m_RoughnessMultiplier",
        displayName: "Roughness Multiplier",
        type: TypeKind.Float,
        offset: 36,
        size: 4,
        category: "Material Overrides",
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        name: "m_MetallicMultiplier",
        displayName: "Metallic Multiplier",
        type: TypeKind.Float,
        offset: 40,
        size: 4,
        category: "Material Overrides",
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        name: "m_BaseColorTint",
        displayName: "Base Color Tint",
        type: TypeKind.Color4,
        offset: 44,
        size: 16,
        category: "Material Overrides",
        tooltip: "Linear HDR albedo multiplier tint.",
      },
    ],
  },

  PointLightComponent: {
    className: "PointLightComponent",
    parentClassName: "Component",
    size: 48,
    category: "Lighting",
    properties: [
      {
        name: "m_LightColor",
        displayName: "Light Color",
        type: TypeKind.Color3,
        offset: 0,
        size: 12,
        category: "Light Properties",
        tooltip: "RGB color of the emitted point light in linear space.",
      },
      {
        name: "m_IntensityLumens",
        displayName: "Intensity (Lumens)",
        type: TypeKind.Float,
        offset: 12,
        size: 4,
        category: "Light Properties",
        min: 0,
        max: 50000,
        step: 100,
        tooltip: "Luminous flux in physical lumens.",
      },
      {
        name: "m_AttenuationRadius",
        displayName: "Radius (m)",
        type: TypeKind.Float,
        offset: 16,
        size: 4,
        category: "Light Properties",
        min: 0.1,
        max: 100,
        step: 0.5,
        tooltip: "Maximum distance this light influences before quadratic falloff drops to zero.",
      },
      {
        name: "m_SourceRadius",
        displayName: "Source Radius (Soft Shadow)",
        type: TypeKind.Float,
        offset: 20,
        size: 4,
        category: "Shadows",
        min: 0.0,
        max: 2.0,
        step: 0.05,
      },
      {
        name: "m_bCastShadows",
        displayName: "Cast Point Shadows",
        type: TypeKind.Bool,
        offset: 24,
        size: 1,
        category: "Shadows",
      },
    ],
  },

  JoltRigidBodyComponent: {
    className: "JoltRigidBodyComponent",
    parentClassName: "Component",
    size: 56,
    category: "Physics",
    properties: [
      {
        name: "m_MotionType",
        displayName: "Motion Type",
        type: TypeKind.Enum,
        offset: 0,
        size: 4,
        category: "Jolt Simulation",
        enumOptions: ["Dynamic", "Static", "Kinematic"],
        tooltip: "Jolt EMotionType: Dynamic simulated with forces; Static unmoving; Kinematic keyframed.",
      },
      {
        name: "m_MassKg",
        displayName: "Mass (kg)",
        type: TypeKind.Float,
        offset: 4,
        size: 4,
        category: "Jolt Simulation",
        min: 0.1,
        max: 10000.0,
        step: 1.0,
      },
      {
        name: "m_Friction",
        displayName: "Friction",
        type: TypeKind.Float,
        offset: 8,
        size: 4,
        category: "Material Surface",
        min: 0.0,
        max: 1.0,
        step: 0.05,
      },
      {
        name: "m_Restitution",
        displayName: "Restitution (Bounciness)",
        type: TypeKind.Float,
        offset: 12,
        size: 4,
        category: "Material Surface",
        min: 0.0,
        max: 1.0,
        step: 0.05,
      },
      {
        name: "m_CollisionLayer",
        displayName: "Collision Layer",
        type: TypeKind.Enum,
        offset: 16,
        size: 4,
        category: "Jolt BroadPhase",
        enumOptions: ["MOVING", "NON_MOVING", "DEBRIS", "SENSOR"],
      },
      {
        name: "m_bEnableGravity",
        displayName: "Enable Gravity",
        type: TypeKind.Bool,
        offset: 20,
        size: 1,
        category: "Jolt Simulation",
      },
      {
        name: "m_LinearDamping",
        displayName: "Linear Damping",
        type: TypeKind.Float,
        offset: 24,
        size: 4,
        category: "Damping",
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
    ],
  },

  CameraComponent: {
    className: "CameraComponent",
    parentClassName: "Component",
    size: 40,
    category: "Camera",
    properties: [
      {
        name: "m_FieldOfViewY",
        displayName: "FOV (Degrees)",
        type: TypeKind.Float,
        offset: 0,
        size: 4,
        category: "Optics",
        min: 20,
        max: 120,
        step: 1.0,
      },
      {
        name: "m_NearClipPlane",
        displayName: "Near Clip",
        type: TypeKind.Float,
        offset: 4,
        size: 4,
        category: "Optics",
        min: 0.01,
        max: 10.0,
        step: 0.05,
      },
      {
        name: "m_FarClipPlane",
        displayName: "Far Clip",
        type: TypeKind.Float,
        offset: 8,
        size: 4,
        category: "Optics",
        min: 10.0,
        max: 50000.0,
        step: 10.0,
      },
      {
        name: "m_bIsPrimary",
        displayName: "Is Primary Camera",
        type: TypeKind.Bool,
        offset: 12,
        size: 1,
        category: "View Target",
      },
    ],
  },
};

export const INITIAL_ACTORS: EngineActor[] = [
  {
    id: "actor-hero-mech",
    name: "Hero_Vanguard_Mech",
    tag: "Player",
    layer: "Default",
    parentId: null,
    childrenIds: ["actor-weapon-socket"],
    transform: {
      position: [0, 1.2, 0],
      rotation: [0, 25, 0],
      scale: [1, 1, 1],
    },
    isStatic: false,
    isVisible: true,
    components: [
      {
        id: "comp-trans-1",
        type: "TransformComponent",
        name: "Transform",
        enabled: true,
        properties: {
          m_LocalPosition: [0, 1.2, 0],
          m_LocalRotation: [0, 25, 0],
          m_LocalScale: [1, 1, 1],
          m_bIsStatic: false,
        },
      },
      {
        id: "comp-mesh-1",
        type: "StaticMeshComponent",
        name: "Mesh: SM_Vanguard_Mech",
        enabled: true,
        properties: {
          m_MeshAssetHandle: "guid-mesh-hero-mech-001",
          m_MaterialAssetHandle: "guid-mat-cyber-titanium",
          m_bCastShadows: true,
          m_bReceiveDecals: true,
          m_RoughnessMultiplier: 0.35,
          m_MetallicMultiplier: 0.85,
          m_BaseColorTint: [0.2, 0.6, 1.0, 1.0],
        },
      },
      {
        id: "comp-phys-1",
        type: "JoltRigidBodyComponent",
        name: "Jolt Physics Body",
        enabled: true,
        properties: {
          m_MotionType: "Dynamic",
          m_MassKg: 750.0,
          m_Friction: 0.6,
          m_Restitution: 0.25,
          m_CollisionLayer: "MOVING",
          m_bEnableGravity: true,
          m_LinearDamping: 0.05,
        },
      },
    ],
  },
  {
    id: "actor-weapon-socket",
    name: "Plasma_Cannon_Rig",
    tag: "Weapon",
    layer: "Default",
    parentId: "actor-hero-mech",
    childrenIds: [],
    transform: {
      position: [0.75, 0.4, 0.3],
      rotation: [0, 0, 0],
      scale: [0.8, 0.8, 0.8],
    },
    isStatic: false,
    isVisible: true,
    components: [
      {
        id: "comp-trans-weapon",
        type: "TransformComponent",
        name: "Transform",
        enabled: true,
        properties: {
          m_LocalPosition: [0.75, 0.4, 0.3],
          m_LocalRotation: [0, 0, 0],
          m_LocalScale: [0.8, 0.8, 0.8],
          m_bIsStatic: false,
        },
      },
      {
        id: "comp-mesh-weapon",
        type: "StaticMeshComponent",
        name: "Mesh: SM_Plasma_Cannon",
        enabled: true,
        properties: {
          m_MeshAssetHandle: "guid-mesh-plasma-cannon",
          m_MaterialAssetHandle: "guid-mat-dark-alloy",
          m_bCastShadows: true,
          m_bReceiveDecals: false,
          m_RoughnessMultiplier: 0.2,
          m_MetallicMultiplier: 0.95,
          m_BaseColorTint: [1.0, 0.3, 0.1, 1.0],
        },
      },
    ],
  },
  {
    id: "actor-sun-light",
    name: "Sun_Directional_Light",
    tag: "Lighting",
    layer: "Default",
    parentId: null,
    childrenIds: [],
    transform: {
      position: [15, 25, 10],
      rotation: [-50, 45, 0],
      scale: [1, 1, 1],
    },
    isStatic: true,
    isVisible: true,
    components: [
      {
        id: "comp-light-sun",
        type: "PointLightComponent",
        name: "Key Sun Light",
        enabled: true,
        properties: {
          m_LightColor: [1.0, 0.95, 0.85],
          m_IntensityLumens: 18500,
          m_AttenuationRadius: 50.0,
          m_SourceRadius: 0.5,
          m_bCastShadows: true,
        },
      },
    ],
  },
  {
    id: "actor-point-light-accent",
    name: "PointLight_Cyber_Neon",
    tag: "Lighting",
    layer: "Default",
    parentId: null,
    childrenIds: [],
    transform: {
      position: [-2.5, 3.0, 1.5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    isStatic: false,
    isVisible: true,
    components: [
      {
        id: "comp-light-accent",
        type: "PointLightComponent",
        name: "Point Light",
        enabled: true,
        properties: {
          m_LightColor: [0.1, 0.8, 1.0],
          m_IntensityLumens: 4200,
          m_AttenuationRadius: 12.0,
          m_SourceRadius: 0.2,
          m_bCastShadows: true,
        },
      },
    ],
  },
  {
    id: "actor-physics-box",
    name: "Physics_Crate_Heavy",
    tag: "Prop",
    layer: "Physics",
    parentId: null,
    childrenIds: [],
    transform: {
      position: [2.5, 0.6, -1.2],
      rotation: [0, 15, 0],
      scale: [1.2, 1.2, 1.2],
    },
    isStatic: false,
    isVisible: true,
    components: [
      {
        id: "comp-trans-box",
        type: "TransformComponent",
        name: "Transform",
        enabled: true,
        properties: {
          m_LocalPosition: [2.5, 0.6, -1.2],
          m_LocalRotation: [0, 15, 0],
          m_LocalScale: [1.2, 1.2, 1.2],
          m_bIsStatic: false,
        },
      },
      {
        id: "comp-mesh-box",
        type: "StaticMeshComponent",
        name: "Mesh: SM_Industrial_Crate",
        enabled: true,
        properties: {
          m_MeshAssetHandle: "guid-mesh-crate",
          m_MaterialAssetHandle: "guid-mat-rusty-iron",
          m_bCastShadows: true,
          m_bReceiveDecals: true,
          m_RoughnessMultiplier: 0.7,
          m_MetallicMultiplier: 0.4,
          m_BaseColorTint: [0.85, 0.65, 0.3, 1.0],
        },
      },
      {
        id: "comp-phys-box",
        type: "JoltRigidBodyComponent",
        name: "Jolt Physics Body",
        enabled: true,
        properties: {
          m_MotionType: "Dynamic",
          m_MassKg: 120.0,
          m_Friction: 0.8,
          m_Restitution: 0.15,
          m_CollisionLayer: "MOVING",
          m_bEnableGravity: true,
          m_LinearDamping: 0.1,
        },
      },
    ],
  },
  {
    id: "actor-terrain-floor",
    name: "Floor_Grid_Platform",
    tag: "Environment",
    layer: "Default",
    parentId: null,
    childrenIds: [],
    transform: {
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [20, 0.2, 20],
    },
    isStatic: true,
    isVisible: true,
    components: [
      {
        id: "comp-mesh-floor",
        type: "StaticMeshComponent",
        name: "Mesh: SM_Platform_Tile",
        enabled: true,
        properties: {
          m_MeshAssetHandle: "guid-mesh-platform",
          m_MaterialAssetHandle: "guid-mat-grid-concrete",
          m_bCastShadows: false,
          m_bReceiveDecals: true,
          m_RoughnessMultiplier: 0.8,
          m_MetallicMultiplier: 0.1,
          m_BaseColorTint: [0.15, 0.18, 0.22, 1.0],
        },
      },
      {
        id: "comp-phys-floor",
        type: "JoltRigidBodyComponent",
        name: "Jolt Static Collider",
        enabled: true,
        properties: {
          m_MotionType: "Static",
          m_MassKg: 0.0,
          m_Friction: 0.9,
          m_Restitution: 0.05,
          m_CollisionLayer: "NON_MOVING",
          m_bEnableGravity: false,
          m_LinearDamping: 0.0,
        },
      },
    ],
  },
];

// ==========================================
// SCENE PRESETS FOR CONSOLE & SCENE MANAGER
// ==========================================
export const ENGINE_SCENE_PRESETS: Record<string, { name: string; description: string; actors: EngineActor[] }> = {
  SciFiHangar: {
    name: "SciFiHangar",
    description: "Industrial mech assembly hangar with Vulkan directional & cyber neon lights, Jolt physics crate, and floor platform.",
    actors: INITIAL_ACTORS,
  },
  PhysicsLab: {
    name: "PhysicsLab",
    description: "Jolt Physics stress-testing arena with dynamic stacking boxes, restitution spheres, and static collision floor.",
    actors: [
      {
        id: "actor-lab-floor",
        name: "Physics_Ground_Plane",
        tag: "Environment",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [24, 0.2, 24] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-floor-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.85, m_MetallicMultiplier: 0.05, m_bCastShadows: false, m_BaseColorTint: [0.12, 0.14, 0.18, 1.0] },
          },
          {
            id: "comp-floor-phys",
            type: "JoltRigidBodyComponent",
            name: "JoltRigidBodyComponent",
            enabled: true,
            properties: { m_MotionType: "Static", m_MassKg: 0, m_Friction: 0.9, m_Restitution: 0.1, m_CollisionLayer: "NON_MOVING" },
          },
        ],
      },
      {
        id: "actor-lab-light",
        name: "Key_Spotlight",
        tag: "Lighting",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 15, 0], rotation: [-90, 0, 0], scale: [1, 1, 1] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-lab-light",
            type: "PointLightComponent",
            name: "PointLightComponent",
            enabled: true,
            properties: { m_LightColor: [1.0, 0.95, 0.9], m_IntensityLumens: 25000, m_AttenuationRadius: 40.0, m_bCastShadows: true },
          },
        ],
      },
      {
        id: "actor-box-1",
        name: "Physics_Crate_Base",
        tag: "Physics",
        layer: "Physics",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 0.6, 0], rotation: [0, 0, 0], scale: [1.2, 1.2, 1.2] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-b1-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.5, m_MetallicMultiplier: 0.8, m_bCastShadows: true, m_BaseColorTint: [0.2, 0.6, 0.9, 1.0] },
          },
          {
            id: "comp-b1-phys",
            type: "JoltRigidBodyComponent",
            name: "JoltRigidBodyComponent",
            enabled: true,
            properties: { m_MotionType: "Dynamic", m_MassKg: 100.0, m_Friction: 0.7, m_Restitution: 0.2, m_CollisionLayer: "MOVING" },
          },
        ],
      },
      {
        id: "actor-box-2",
        name: "Physics_Crate_Mid",
        tag: "Physics",
        layer: "Physics",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 1.9, 0], rotation: [0, 10, 0], scale: [1.1, 1.1, 1.1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-b2-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.4, m_MetallicMultiplier: 0.6, m_bCastShadows: true, m_BaseColorTint: [0.9, 0.4, 0.2, 1.0] },
          },
          {
            id: "comp-b2-phys",
            type: "JoltRigidBodyComponent",
            name: "JoltRigidBodyComponent",
            enabled: true,
            properties: { m_MotionType: "Dynamic", m_MassKg: 75.0, m_Friction: 0.6, m_Restitution: 0.25, m_CollisionLayer: "MOVING" },
          },
        ],
      },
      {
        id: "actor-box-3",
        name: "Physics_Crate_Top",
        tag: "Physics",
        layer: "Physics",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 3.1, 0], rotation: [0, -15, 0], scale: [1.0, 1.0, 1.0] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-b3-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.3, m_MetallicMultiplier: 0.9, m_bCastShadows: true, m_BaseColorTint: [0.8, 0.8, 0.2, 1.0] },
          },
          {
            id: "comp-b3-phys",
            type: "JoltRigidBodyComponent",
            name: "JoltRigidBodyComponent",
            enabled: true,
            properties: { m_MotionType: "Dynamic", m_MassKg: 50.0, m_Friction: 0.5, m_Restitution: 0.3, m_CollisionLayer: "MOVING" },
          },
        ],
      },
      {
        id: "actor-sphere-bounce",
        name: "High_Bounciness_Sphere",
        tag: "Physics",
        layer: "Physics",
        parentId: null,
        childrenIds: [],
        transform: { position: [3.5, 4.0, 0], rotation: [0, 0, 0], scale: [0.8, 0.8, 0.8] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-sph-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.1, m_MetallicMultiplier: 0.1, m_bCastShadows: true, m_BaseColorTint: [0.1, 0.9, 0.4, 1.0] },
          },
          {
            id: "comp-sph-phys",
            type: "JoltRigidBodyComponent",
            name: "JoltRigidBodyComponent",
            enabled: true,
            properties: { m_MotionType: "Dynamic", m_MassKg: 20.0, m_Friction: 0.2, m_Restitution: 0.85, m_CollisionLayer: "MOVING" },
          },
        ],
      },
    ],
  },
  CyberCity: {
    name: "CyberCity",
    description: "Cyberpunk urban alleyway with vibrant neon lighting (Cyan, Magenta, Amber) and surveillance drone actor.",
    actors: [
      {
        id: "actor-cyber-floor",
        name: "Wet_Asphalt_Road",
        tag: "Environment",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [30, 0.2, 30] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-cyber-floor-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.15, m_MetallicMultiplier: 0.8, m_bCastShadows: false, m_BaseColorTint: [0.08, 0.09, 0.12, 1.0] },
          },
        ],
      },
      {
        id: "actor-drone-scout",
        name: "Recon_Drone_Vanguard",
        tag: "Character",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 3.2, 0], rotation: [0, 45, 10], scale: [1.2, 0.4, 1.2] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-drone-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.2, m_MetallicMultiplier: 0.95, m_bCastShadows: true, m_BaseColorTint: [0.1, 0.1, 0.12, 1.0] },
          },
          {
            id: "comp-drone-move",
            type: "CharacterMovementComponent",
            name: "CharacterMovementComponent",
            enabled: true,
            properties: { m_MaxWalkSpeed: 45.0, m_MaxAcceleration: 120.0, m_GravityZ: -4.9, m_bIsFlying: true },
          },
        ],
      },
      {
        id: "actor-neon-cyan",
        name: "Neon_Light_Cyan",
        tag: "Lighting",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [-4, 2.5, -3], rotation: [0, 0, 0], scale: [1, 1, 1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-light-cyan",
            type: "PointLightComponent",
            name: "PointLightComponent",
            enabled: true,
            properties: { m_LightColor: [0.0, 0.9, 1.0], m_IntensityLumens: 9500, m_AttenuationRadius: 18.0, m_bCastShadows: true },
          },
        ],
      },
      {
        id: "actor-neon-pink",
        name: "Neon_Light_Magenta",
        tag: "Lighting",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [4, 3.0, 2], rotation: [0, 0, 0], scale: [1, 1, 1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-light-pink",
            type: "PointLightComponent",
            name: "PointLightComponent",
            enabled: true,
            properties: { m_LightColor: [1.0, 0.1, 0.7], m_IntensityLumens: 8800, m_AttenuationRadius: 16.0, m_bCastShadows: true },
          },
        ],
      },
    ],
  },
  VulkanPBRShowcase: {
    name: "VulkanPBRShowcase",
    description: "Material calibration stage with metallic, roughness, and dielectric PBR spheres under studio 3-point lighting.",
    actors: [
      {
        id: "actor-studio-floor",
        name: "Studio_Pedestal_Platform",
        tag: "Environment",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [16, 0.2, 16] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-studio-floor-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.9, m_MetallicMultiplier: 0.0, m_bCastShadows: false, m_BaseColorTint: [0.18, 0.18, 0.2, 1.0] },
          },
        ],
      },
      {
        id: "actor-sphere-gold",
        name: "Sphere_PBR_Gold",
        tag: "PBR_Material",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [-3, 1.0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-gold-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.15, m_MetallicMultiplier: 1.0, m_bCastShadows: true, m_BaseColorTint: [1.0, 0.76, 0.33, 1.0] },
          },
        ],
      },
      {
        id: "actor-sphere-chrome",
        name: "Sphere_PBR_Chrome",
        tag: "PBR_Material",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 1.0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-chrome-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.02, m_MetallicMultiplier: 1.0, m_bCastShadows: true, m_BaseColorTint: [0.95, 0.95, 0.98, 1.0] },
          },
        ],
      },
      {
        id: "actor-sphere-rough",
        name: "Sphere_PBR_Ceramic",
        tag: "PBR_Material",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [3, 1.0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        isStatic: false,
        isVisible: true,
        components: [
          {
            id: "comp-rough-mesh",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.85, m_MetallicMultiplier: 0.0, m_bCastShadows: true, m_BaseColorTint: [0.8, 0.2, 0.2, 1.0] },
          },
        ],
      },
      {
        id: "actor-pbr-key-light",
        name: "Studio_Key_Light",
        tag: "Lighting",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [5, 8, 5], rotation: [-45, 45, 0], scale: [1, 1, 1] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-pbr-key",
            type: "PointLightComponent",
            name: "PointLightComponent",
            enabled: true,
            properties: { m_LightColor: [1.0, 0.98, 0.92], m_IntensityLumens: 18000, m_AttenuationRadius: 30.0, m_bCastShadows: true },
          },
        ],
      },
    ],
  },
  EmptyScene: {
    name: "EmptyScene",
    description: "Minimalist blank canvas with default transform origin and directional ambient light.",
    actors: [
      {
        id: "actor-empty-floor",
        name: "Grid_Floor",
        tag: "Environment",
        layer: "Default",
        parentId: null,
        childrenIds: [],
        transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [20, 0.1, 20] },
        isStatic: true,
        isVisible: true,
        components: [
          {
            id: "comp-empty-floor",
            type: "StaticMeshComponent",
            name: "StaticMeshComponent",
            enabled: true,
            properties: { m_RoughnessMultiplier: 0.8, m_MetallicMultiplier: 0.1, m_bCastShadows: false, m_BaseColorTint: [0.15, 0.18, 0.22, 1.0] },
          },
        ],
      },
    ],
  },
};

